CREATE TABLE `user_points_accounts` (
  `account_id` bigint NOT NULL AUTO_INCREMENT COMMENT '账户唯一标识',
  `user_id` int NOT NULL COMMENT '关联用户ID',
  `available_points` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '可用积分余额',
  `total_earned` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '累计获得积分',
  `total_consumed` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '累计消耗积分',
  `last_earn_time` datetime DEFAULT NULL COMMENT '最后获得积分时间',
  `last_consume_time` datetime DEFAULT NULL COMMENT '最后消耗积分时间',
  `account_level` enum('bronze','silver','gold','diamond') COLLATE utf8mb4_unicode_ci DEFAULT 'bronze',
  `is_active` tinyint(1) DEFAULT '1',
  `freeze_reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '冻结原因',
  `behavior_score` decimal(5,2) DEFAULT '0.00',
  `activity_level` enum('low','medium','high','premium') COLLATE utf8mb4_unicode_ci DEFAULT 'medium',
  `preference_tags` json DEFAULT NULL COMMENT '用户偏好标签JSON',
  `last_behavior_time` datetime DEFAULT NULL COMMENT '最后行为时间',
  `recommendation_enabled` tinyint(1) DEFAULT '1',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`account_id`),
  UNIQUE KEY `user_id` (`user_id`),
  UNIQUE KEY `uk_user_id` (`user_id`),
  KEY `idx_available_points` (`available_points`),
  KEY `idx_account_level` (`account_level`),
  KEY `idx_last_earn_time` (`last_earn_time`),
  KEY `idx_is_active` (`is_active`),
  KEY `idx_behavior_score` (`behavior_score`),
  KEY `idx_activity_level` (`activity_level`),
  KEY `idx_last_behavior_time` (`last_behavior_time`),
  KEY `idx_recommendation_enabled` (`recommendation_enabled`),
  KEY `idx_behavior_activity` (`behavior_score`,`activity_level`),
  KEY `idx_upa_available_points` (`available_points`),
  KEY `idx_upa_account_level` (`account_level`),
  KEY `idx_upa_is_active` (`is_active`),
  KEY `idx_upa_behavior_score` (`behavior_score`),
  KEY `idx_upa_activity_level` (`activity_level`),
  CONSTRAINT `user_points_accounts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=108 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户积分账户表 - 积分系统核心表'